#!/usr/bin/python3

"""Reads request for log find task from STDIN and prints the lines that
were found"""

import sys
import logging

from config import Config
from readlog import ReadLog

lrlog = logging.getLogger('backup.readlog')
if __name__ == '__main__':
    line = sys.stdin.readline().strip()
    content_type = "text/x-plain-ask"
    if line.startswith("content-type: "):
        content_type = line[len("content-type: "):]
        line = sys.stdin.readline().strip()
    Config.init_file(line)
    log.get_logger('asdf') # TODO

    print(ReadLog.standalone(None))
