#!/usr/bin/python3

"""Reads request for log find task from STDIN and prints the lines that
were found"""

import sys

from config import Config
from taggedlog import TaggedLog

line = sys.stdin.readline().strip()
content_type = "text/x-plain-ask"
if line.startswith("content-type: "):
    content_type = line[len("content-type: "):]
    line = sys.stdin.readline().strip()

try:
    config = Config(line)
except FileNotFoundError as fnfe:
    print("{} {}".format(fnfe.strerror, fnfe.filename), file=sys.stderr)
    sys.exit(1)
status_file = config.find('status', 'file', None)
if status_file is None:
    print("Status file cannot be determined", file=sys.stderr)
    sys.exit(1)
log_obj = TaggedLog(status_file, 'r')

subject_list = []
for line in sys.stdin:
    if line.strip() == "":
        break
    subject_list.append(line.strip())

action = 'list'
for line in sys.stdin:
    action = line.strip()

entries = log_obj.find(subjects=subject_list, action=action)
print(entries)
sys.exit(0)
