#!/usr/bin/python3

"""Reads new log entries from STDIN and adds them to the appropriate
log. Communication follows text/x-plain-log type"""

import sys

from config import Config
from taggedlog import TaggedLog, FromStream

line = sys.stdin.readline().strip()
content_type = "text/x-plain-log"
if line.startswith("content-type: "):
    content_type = line[len("content-type: "):]
    line = sys.stdin.readline().strip()

# TODO use Config.get_config()
# TODO use logger
log = log.getLogger('receiver', 30)
config = Config.get_config(line, log)
status_file = config.find('status', 'file', None)
if status_file is None:
    log.warning("Status file cannot be determined")
    sys.exit(1)
log_obj = TaggedLog(status_file, 'a+')

entry = FromStream(sys.stdin, content_type)

log_obj.append(entry)
sys.exit(0)
