#!/usr/bin/python3

import sys

from config import Config
from taggedlog import *

line = sys.stdin.readline().strip()
content_type = "text/x-plain-log"
if line.startswith("content-type: "):
    content_type = line[len("content-type: "):]
    line = sys.stdin.readline().strip()

config = Config(line)
entry = FromStream(sys.stdin, content_type)

log_obj = TaggedLog(config.find('status', 'file', ''), 'a+')
log_obj.append(entry)
