#!/bin/bash

exec_dir=$(dirname $0)
source $exec_dir/notify.sh

rc=rc.ini
nonotify=""
temponly=0
addfiles=""
while [ $# -gt 0 ]; do
    case "$1" in
        -a|--add)
            shift;
            if [ -n "$1" ]; then
                addfiles=$1
            fi
            shift;
        ;;
        -c|--config)
            shift;
            if [ -n "$1" ]; then
                rc=$1
            fi
            shift;
        ;;
        # this is the standard behavior
        -n|--notify)
            shift;
            nonotify=""
        ;;
        # turn off notify-send
        -no-n|--no-notify)
            shift;
            nonotify=1
        ;;
        -q|--quiet)
            shift;
            verbose=""
        ;;
        -v|--verbose)
            shift;
            verbose=1
        ;;
        *)
            shift;
        ;;
    esac
done

source $exec_dir/helpers.sh
source $exec_dir/find_config.sh

gitdir=$($config --section git --key directory --default "$PWD")
gitcmd="git -C $gitdir"

for file in $addfiles $($config --section git --key add --default ''); do
    verbose_echo "Adding $file"
    $gitcmd add $file 2>/dev/null
done
if [ -n "$($config --section git --key add_all --default '')" ]; then
    verbose_echo "Adding all tracked files"
    git add -u
fi

if $gitcmd status --porcelain | grep -qv ^??; then
    # there is something modified, so we will commit:
    msg=$(date +"$($config --section git --key small_message --default "small backup")")
    verbose_echo "Committing $msg"
    $gitcmd commit -qm "$msg"
fi

notify SUCCESS "Current commit is $($gitcmd log -1 --format=%H)"
exit 0;
