#!/usr/bin/python3

"""Creates a small git commit"""

import argparse
from datetime import datetime
from pathlib import Path
import sys
from gitversion import Git
from config import Config
from notify import Notify
import log

parser = argparse.ArgumentParser(description="""Creates a small commit""")
parser.add_argument('--add', '-a',
    action='append',
    required=False,
    default=[]
)
Config.add_options(parser)
log.add_options(parser)
Notify.add_options(parser)
args = parser.parse_args()

log = log.get_logger('small_commit', args)
config = Config.get_config(args)
notify = Notify(config, show=not args.notification_dontshow)
git = Git(config.find('git', 'directory', Path.cwd()))

addable_files = args.add
for pattern in config.find('git', 'add', '').split():
    path = Path(pattern)
    addable_files.extend(path.parent.glob(path.name))
for curr_file in addable_files:
    log.info("Adding %s", curr_file)
    git.command('add', curr_file)
if config.find('git', 'add_all', False):
    log.info("Adding all tracked files")
    git.command('add', '-u')

if git.there_are_untracked_files():
    msg = config.find('git', 'small_message', 'small backup').format(datetime.now())
    log.info("Commiting %s", msg)
    git.command('commit', '-qm', msg)

notify.success("Current commit is", git.hash())
sys.exit(0)
